name: Publish package to NuGet

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Build, pack and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish SteamCSharp to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: SteamCSharp/SteamCSharp/SteamCSharp.csproj
        PACKAGE_NAME: SteamCSharp
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
